import { GetNodesResponse } from "./NodeService";

export const getNodes = (): GetNodesResponse[] => {
  return [
    {
      id: 1,
      caseId: null,
      caseLabel: null,
      locationFrom: null,
      locationTo: null,
      type: "delivery",
      quantity: 23234,
      user: "Jake Maguire",
      time: "2023-10-01 10:10:00",
    },
    {
      id: 2,
      caseId: 123,
      caseLabel: "CAS2414",
      locationFrom: {
        id: 1,
        name: "A012",
        hub: 2027,
        siteId: 1,
        siteName: "CH001 (Chippenham, UK)",
        type: 4,
      },
      locationTo: {
        id: 2,
        name: "A047",
        hub: 3024,
        siteId: 1,
        siteName: "CH001 (Chippenham, UK)",
        type: 4,
      },
      type: "goodsIn",
      quantity: 23234,
      user: "Jake Maguire",
      time: "2023-10-01 10:10:00",
    },
    {
      id: 3,
      caseId: 123,
      caseLabel: "CAS2414",
      locationFrom: {
        id: 1,
        name: "A047",
        hub: 3024,
        siteId: 1,
        siteName: "CH001 (Chippenham, UK)",
        type: 4,
      },
      locationTo: {
        id: 2,
        name: "B389",
        hub: 4023,
        siteId: 1,
        siteName: "CH001 (Chippenham, UK)",
        type: 4,
      },
      type: "move",
      quantity: 23234,
      user: "Jake Maguire",
      time: "2023-10-01 10:10:00",
    },
    {
      id: 4,
      caseId: 123,
      caseLabel: "CAS2414",
      locationFrom: {
        id: 2,
        name: "B389",
        hub: 4023,
        siteId: 1,
        siteName: "CH001 (Chippenham, UK)",
        type: 4,
      },
      locationTo: {
        id: 2,
        name: "B345",
        hub: 4023,
        siteId: 1,
        siteName: "CH001 (Chippenham, UK)",
        type: 4,
      },
      type: "palletMove",
      quantity: 23234,
      user: "Jake Maguire",
      time: "2023-10-01 10:10:00",
    },
    {
      id: 5,
      caseId: 123,
      caseLabel: "CAS2414",
      locationFrom: {
        id: 2,
        name: "B389",
        hub: 4023,
        siteId: 1,
        siteName: "CH001 (Chippenham, UK)",
        type: 4,
      },
      locationTo: {
        id: 2,
        name: "B345",
        hub: 4023,
        siteId: 1,
        siteName: "CH001 (Chippenham, UK)",
        type: 4,
      },
      type: "transit",
      quantity: 23234,
      user: "Jake Maguire",
      time: "2023-10-01 10:10:00",
    },
    {
      id: 6,
      caseId: 123,
      caseLabel: "CAS2414",
      locationFrom: {
        id: 3,
        name: "B389",
        hub: 4023,
        siteId: 1,
        siteName: "CH001 (Chippenham, UK)",
        type: 4,
      },
      locationTo: {
        id: 4,
        name: "L382",
        hub: 8923,
        siteId: 2,
        siteName: "MA001 (Madrid, ES)",
        type: 4,
      },
      type: "move",
      quantity: 23234,
      user: "Jake Maguire",
      time: "2023-10-01 10:10:00",
    },
    {
      id: 7,
      caseId: 123,
      caseLabel: "CAS2414",
      locationFrom: {
        id: 4,
        name: "L382",
        hub: 8923,
        siteId: 2,
        siteName: "MA001 (Madrid, ES)",
        type: 4,
      },
      locationTo: {
        id: 4,
        name: "M934",
        hub: 4535,
        siteId: 2,
        siteName: "MA001 (Madrid, ES)",
        type: 4,
      },
      type: "move",
      quantity: 23234,
      user: "Jake Maguire",
      time: "2023-10-01 10:10:00",
    },
    {
      id: 8,
      caseId: 123,
      caseLabel: "CAS2414",
      locationFrom: {
        id: 4,
        name: "M934",
        hub: 4535,
        siteId: 2,
        siteName: "MA001 (Madrid, ES)",
        type: 4,
      },
      locationTo: {
        id: 4,
        name: "H734 - Shelf",
        hub: 4535,
        siteId: 2,
        siteName: "MA001 (Madrid, ES)",
        type: 4,
      },
      type: "bookIn",
      quantity: 23234,
      user: "Jake Maguire",
      time: "2023-10-01 10:10:00",
    },
  ];
};
