trigger:
  branches:
    include:
      - main
      - pipeline
pr: none
stages:
  - stage: Docker
    displayName: Build & Push Docker image to AWS ECR
    jobs:
      - job: Build_and_Push
        displayName: Build & Push Docker image
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build an image
            inputs:
              command: build
              dockerfile: "$(Build.SourcesDirectory)/Dockerfile"
              buildContext: "$(Build.SourcesDirectory)"
              repository: "huboo/apps/warehouse-portal-php"

          - task: ECRPushImage@1
            inputs:
              awsCredentials: "aws-azure-devops-huboo-ops" # Name of the AWS service connection
              regionName: "eu-west-2"
              imageSource: "imagename"
              sourceImageName: $(DOCKER_REPOSITORY_NAME)
              sourceImageTag: $(Build.BuildId)
              pushTag: latest
              repositoryName: $(DOCKER_REPOSITORY_NAME)
